import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 6]])

A

A[1:, 1:2]

In [30]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 6]])

print(A)

A[1:3, 1:]

"""
4 5
7 8
"""

# print(A[1:3, :2])
print()
"""
2 3
5 6
"""

print(A[0:2, 1:])



[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]]
()
[[2 3]
 [5 6]]


In [36]:

# vector
L = np.array([1, 2, 4, 5, 6])

# vector
M = np.array([2, 3, 5, 6, 7])

dot = np.dot(L, M)
dot.sum()

100.0

In [38]:


# transpose of a matrix
trnA = A.T
print(trnA)



[[1 4 7 4]
 [2 5 8 5]
 [3 6 9 6]]


In [40]:

C = np.array([1, 10, 20])
print("A: \n", A)
print()

print("C: \n", C)
print()

print("A*C: \n", A*C)

print()

print("A dot C: ", np.dot(A, C))


('A: \n', array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 6]]))
()
('C: \n', array([ 1, 10, 20]))
()
('A*C: \n', array([[  1,  20,  60],
       [  4,  50, 120],
       [  7,  80, 180],
       [  4,  50, 120]]))
()
('A dot C: ', array([ 81, 174, 267, 174]))


In [ ]:

B = np.array([[1, 2], [2, 3]])
C = np.array([[3, 5], [6, 7, 8]])

B = np.mat(B)
C = np.mat(C)

D = B * C
print(D)

# B = A * C
# print(B)


In [ ]:
from google.colab import files

uploaded = files.upload()

In [3]:
import panda as pd

ModuleNotFoundError: No module named 'panda'