In [23]:
import numpy as np

In [24]:
#inverse matrix
x = np.array([[3, 4], [2, 16]])
y = np.linalg.inv(x)


#transpose of a matrix

X = np.array([[1, 2104, 5, 1, 45], [1, 1416, 3, 2, 40], [1, 1534, 3, 2, 30], [1, 852, 2, 1, 36]])
y = np.array([[460], [232], [315], [178]])
print(y)
print(X)
print('\n\n')
print(X.T)

# matrix multiplication

temp_theta1 = np.linalg.inv(np.dot((X.T), X))
temp_theta2 = np.dot(X.T, y)
theta = np.dot(temp_theta1, temp_theta2)

theta

[[460]
 [232]
 [315]
 [178]]
[[   1 2104    5    1   45]
 [   1 1416    3    2   40]
 [   1 1534    3    2   30]
 [   1  852    2    1   36]]



[[   1    1    1    1]
 [2104 1416 1534  852]
 [   5    3    3    2]
 [   1    2    2    1]
 [  45   40   30   36]]


array([[-384.    ],
       [   0.5625],
       [ -96.    ],
       [ -80.    ],
       [  -4.    ]])